const Strings = {
	email_is_missing : "Email is missing",
	please_input_an_email_address : "Please input an email address",
	password_is_missing : "Password is missing",
	password_confirmation_is : "Password confirmation is missing",
	passwords_must_match : "Passwords must match",
	sorry_cannot_submit_this_form : "Sorry, cannot submit this form at the moment",
	user_denied_permissions : "User denied permissions!",
	sorry_the_invite_code_did_not : "Sorry, the invite code did not correspond to any team",
	this_method_should_only_be : "This method should only be called when user is authenticated",
	about_this_study : "About this study",
	are_you_sure : "Are you sure?",
	this_action_is_irreversible : "This action is irreversible",
	cancel : "Cancel",
	your_profile : "Your profile",
	invite_code_is_missing : "Invite code is missing",
	invite_code_must_have_6 : "Invite code must have 6 digits",
	join_a_team : "Join a team",
	invite_code : "Invite code",
	team_name_is_missing : "Team name is missing",
	create_a_team : "Create a team",
	name : "Name",
	the_blueberries : "The Blueberries",
	description : "Description",
	your_amazing_team_description : "Your amazing team description",
	are_you_sure : "Are you sure?",
	you_will_be_able_to_join_this : "You will be able to join this team again",
	cancel : "Cancel",
	no_description : "No description",
	teams_leaderboard : "Teams leaderboard",
	journal_tabs : "Journal tabs",
	you_did_not_have_any_notes : "You did not have any notes for this day",
	you_did_not_have_any : "You did not have any activities for this day",
	add_a_note : "Add a note",
	note : "Note",
	a_note_to_your_future_self : "A note to your future self",
	next : "Next",
	scroll_or_read_to_the_end_to : "Scroll or read to the end to continue",
	please_check_this_box_to : "Please check this box to continue",
	enroll : "Enroll!",
	i_have_read_the_provided : "I have read the provided participant information and consent to take part in the study",
	i_am_a_member_of_staff_or_a : "I am a member of staff or a student at the University of Southampton, and I am at least 18 years old.",
	i_understand_that_i_must_be : "I understand that I must be employed in a participating faculty or service, and that in some faculties or services I should discuss or raise participation with my line manager, as directed by my faculty or service.",
	i_understand_that_physical : "I understand that physical activity can pose the risk of injury, and I have checked that it is safe for me to take part",
	new_password : "New password",
	new_password : "New password",
	repeat_new_password : "Repeat new password",
	you_must_register_with_a : "You must register with a valid soton.ac.uk email address",
	this_email_is_associated_with : "This email is associated with an account. Please log in instead",
	register_to_continue : "Register to continue",
	register : "Register",
	university_email : "University email",
	password : "Password",
	repeat_password : "Repeat password",
	password_is_missing : "Password is missing",
	email_or_password_did_not : "Email or password did not match our record",
	login_to_continue : "Login to continue",
	login : "Login",
	email : "Email",
	password : "Password",
	reset_your_password : "Reset your password",
	if_your_email_is_in_our : "If your email is in our records, we will send you an email ",
	continue : "Continue",
	email : "Email",
	confirm_your_account : "Confirm your account",
	xb_app_logo : "XB App logo",
	your_first_name_is_missing : "Your first name is missing",
	your_last_name_is_missing : "Your last name is missing",
	department_is_missing : "Department is missing",
	lets_roll : "Lets roll!",
	first_name : "First name",
	last_name : "Last name",
	department : "Department",
	campus : "Campus",
	office : "Office",
	what_move_do_you_want_to_do : "What move do you want to do?",
	tap_on_the_time_display_to : "Tap on the time display to adjust time",
	a_minute_has_passed : "A minute has passed",
	youtube_video_player : "YouTube video player",
	this_field_must_be_a_number : "This field must be a number",
	this_field_is_missing : "This field is missing",
	this_field_is_missing : "This field is missing",
	you_need_to_time_this : "You need to time this activity!",
	this_field_must_be_checked : "This field must be checked",
	this_field_is_missing : "This field is missing",
	retake_another_picture : "Retake another picture",
	take_a_picture : "Take a picture",
	please_review_the_estimation : "Please review the estimation. Note that the percentages do not necessarily add up to 100 as ingredients like rice counts neither as red nor green",
	a_good_picture_must_show_your : "A good picture must show your meal as a whole. Try not to get other objects in the picture to get an accurate estimation",
	green_ : "Green (%)",
	red_ : "Red (%)",
	heart_rate_measure : "Heart rate measure illustration",
	next : "Next",
	submit : "Submit",

};

export default Strings;