const Strings = {
	today : "Hoy",
	boxes : "Cajas",
	journal : "Diario",
	settings : "Configuración",
	teams : "Equipos",
	email_is_missing : "Falta el correo electrónico",
	please_input_an_email_address : "Por favor ingrese una dirección de correo electrónico",
	password_is_missing : "Falta la contraseña",
	password_confirmation_is : "Falta la confirmación de contraseña",
	passwords_must_match : "Las contraseñas deben coincidir",
	sorry_cannot_submit_this_form: "Lo sentimos no podemos enviar este formulario en este momento",
	user_denied_permissions : "¡Permisos denegados al usuario!",
	sorry_the_invite_code_did_not : "Lo sentimos el código de invitación no correspondía a ningún equipo",
	this_method_should_only_be : "Este método solo debe llamarse cuando el usuario está autenticado",
	welcome_to_spring_2023_xb : "¡Bienvenido a la demostración de XB de primavera de 2023! Elija un cuadro a continuación para comenzar.",
	pick_an_experiment : "Elija un experimento",
	day: "Día",
    days: "Días",
	there_is_nothing_to_do_for : "No hay nada que hacer para este día",
	congratulations_you_have : "¡Felicidades! Has completado este experimento.",
	redo_experiment : "Rehacer experimento",
	about_this_study : "Acerca de este estudio",
	are_you_sure : "Estas seguro",
	this_action_is_irreversible : "Esta acción es irreversible",
	cancel : "Cancelar",
	ok : "DE ACUERDO",
	about : "Acerca de",
	app_theme : "Tema de la aplicación",
	log_out : "Finalizar la sesión",
	you_have_requested_your : "Ha solicitado que se elimine su cuenta. Estaremos en contacto pronto.",
	sorry_your_account_cannot_be : "Lo sentimos, tu cuenta no se puede eliminar en este momento.",
	delete_your_account : "Elimina tu cuenta",
	your_profile : "Tu perfil",
	invite_code_is_missing : "Falta el código de invitación",
	invite_code_must_have_6 : "El código de invitación debe tener 6 dígitos",
	join_a_team : "Únete a un equipo",
	invite_code : "código de invitación",
	an_invite_code_is_a_unique : "Un código de invitación es un código único de 6 dígitos asignado a cada equipo. Pídele al dueño o a cualquier miembro del equipo al que quieras unirte que continúe.",
	team_name_is_missing : "Falta el nombre del equipo",
	create_a_team : "Crea un equipo",
	name : "Nombre",
	the_blueberries : "Los arándanos",
	description : "Descripción",
	your_amazing_team_description : "La increíble descripción de tu equipo",
	once_this_team_is_created_you : "Una vez creado este equipo, puedes comenzar a invitar personas dándoles el código de invitación.",
	you_are_currently_not_in_a : "Actualmente no estás en un equipo",
	join : "Unirse",
	or : "O",
	create_one : "Crea uno",
	you_will_be_able_to_join_this : "Podrás unirte a este equipo nuevamente",
	welcome : "Bienvenido",
	no_description : "Sin descripción",
	members : "Miembros",
	member_s_ : "miembro(s)",
	teams_leaderboard : "Tabla de clasificación de equipos",
	leaderboard : "Tabla de clasificación",
	leave_team : "dejar el equipo",
	this_feature_is_coming_soon : "Esta característica estará disponible próximamente",
	stay_tuned : "Manténganse al tanto",
	you : "Tú",
	owner : "Dueño",
	journal_tabs : "Pestañas del diario",
	you_did_not_have_any_notes : "No tenías ninguna nota para este día",
	you_did_not_have_any : "No tenías ninguna actividad para este día",
	add_a_note : "Añadir una nota",
	note : "Nota",
	a_note_to_your_future_self : "Una nota para tu yo futuro",
	a_summary_of_what_you_have : "Un resumen de lo que has hecho hasta ahora",
	daily : "A diario",
	weekly : "Semanalmente",
	activity : "Actividad",
	your_meal_today_consisted_of : "Su comida de hoy consistió en",
	your_meal_today_consisted_of_2 : "% verde y",
	your_meal_today_consisted_of_3 : "% rojo.",
	sorry_we_do_not_have_any_data : "Lo sentimos, no tenemos ningún dato por ahora",
	feel_free_to_jot_down : "
Siéntete libre de anotar cualquier cosa que quieras recordar de este día. Es sólo para su uso y siéntase libre de editarlo en cualquier momento.",
	next : "Próximo",
	scroll_or_read_to_the_end_to : "Desplácese o lea hasta el final para continuar",
	please_check_this_box_to : "Por favor marque esta casilla para continuar",
	enroll : "¡Inscribirse!",
	just_a_few_things : "Sólo unas cuantas cosas...",
	i_have_read_the_provided : "He leído la información del participante proporcionada y doy mi consentimiento para participar en el estudio",
	i_am_a_member_of_staff_or_a : "Soy miembro del personal o estudiante de la Universidad de Southampton y tengo al menos 18 años.",
	i_understand_that_i_must_be : "Entiendo que debo estar empleado en una facultad o servicio participante, y que en algunas facultades o servicios debo discutir o plantear la participación con mi superior inmediato, según lo indique mi facultad o servicio.",
	i_understand_that_physical : "Entiendo que la actividad física puede suponer un riesgo de lesión y he comprobado que es seguro para mí participar",
	you_have_successfully_reset : "¡Has restablecido exitosamente tu contraseña!",
	new_password : "Nueva contraseña",
	repeat_new_password : "Repetir nueva contraseña",
	you_must_register_with_a : "Debes registrarte con un válido ",
	you_must_register_with_a_2 : " dirección de correo electrónico",
	this_email_is_associated_with : "Este correo electrónico está asociado a una cuenta. Por favor inicia sesión en su lugar",
	register_to_continue : "Regístrate para continuar",
	register : "Regístrese",
	university_email : "Correo electrónico de la universidad",
	password : "Contraseña",
	repeat_password : "Repita la contraseña",
	already_had_an_account_login : "¿Ya tenías una cuenta? Acceso",
	email_or_password_did_not : "El correo electrónico o la contraseña no coinciden con nuestro registro",
	login_to_continue : "Inicia sesión para continuar",
	login : "Acceso",
	email : "Correo electrónico",
	not_yet_a_user_register : "¿Aún no eres usuario? Regístrate",
	forgotten_password : "¿Olvidaste tu contraseña?",
	reset_your_password : "Restablece tu contraseña",
	if_your_email_is_in_our : "Si su correo electrónico está en nuestros registros, le enviaremos un correo electrónico",
	continue : "Continuar",
	confirm_your_account : "Confirma tu cuenta",
	sorry_we_cannot_confirm_this : "Lo sentimos, no podemos confirmar esta cuenta. O ha confirmado su cuenta o ha esperado demasiado para confirmar este correo electrónico. Inicie sesión con sus credenciales registradas y siga las instrucciones.",
	account_confirmed_you_can_now : "Cuenta confirmada. Ahora puedes continuar en la aplicación",
	we_have_sent_you_an_email_to : "Le hemos enviado un correo electrónico para confirmar su cuenta",
	resend_confirmation_email : "Reenviar correo electrónico de confirmación",
	confirmed_login : "¿Confirmado? Acceso",
	percent_completed : "% completado",
	day_s_ : "Día(s)",
	xb_app_logo : "Logotipo de la aplicación XB",
	you_havent_got_any_task_today : "No tienes ninguna tarea hoy",
	explore_what_you_can_do_in : "Las tareas aparecerán aquí cuando hayas iniciado algunos experimentos",
	todays_experiments : "Los experimentos de hoy",
	read : "Lea",
	less : "menos",
	more : "más",
	your_first_name_is_missing : "Falta tu nombre",
	your_last_name_is_missing : "Falta tu apellido",
	department_is_missing : "Falta el departamento",
	lets_roll : "Lets roll!",
	first_name : "First name",
	last_name : "Last name",
	department : "Department",
	campus : "Campus",
	office : "Office",
	exercise_is_safe_and : "Exercise is safe and beneficial for most people, but some people should check with their doctor before changing their physical activity patterns. Use the",
	par_questionnaire : "PAR Questionnaire",
	exercise_is_safe_and_2 : "and/or consult your GP before engaging in physical activity.",
	what_move_do_you_want_to_do : "What move do you want to do?",
	click_the_button_below_to_add : "Click the button below to add a movement, then time yourself doing it. Or if you have done it in on your own, tap Next. Repeat 4 to 8 times if possible.",
	add : "Add",
	tap_on_the_time_display_to : "Tap on the time display to adjust time",
	a_minute_has_passed : "A minute has passed",
	youtube_video_player : "YouTube video player",
	this_field_must_be_a_number : "This field must be a number",
	this_field_is_missing : "This field is missing",
	you_need_to_time_this : "You need to time this activity!",
	this_field_must_be_checked : "This field must be checked",
	retake_another_picture : "Retake another picture",
	take_a_picture : "Take a picture",
	please_review_the_estimation : "Please review the estimation. Note that the percentages do not necessarily add up to 100 as ingredients like rice counts neither as red nor green",
	a_good_picture_must_show_your : "A good picture must show your meal as a whole. Try not to get other objects in the picture to get an accurate estimation",
	green : "Green (%)",
	red : "Red (%)",
	the_original_picture_has_been : "The original picture has been re-coloured for you to see if the estimation is correct. Feel free to modify the estimations",
	heart_rate_measure : "Heart rate measure illustration",
	find_your_pulse_by_firmly : "Find your pulse by firmly gripping your wrist like in the diagram below. Count your heartbeats for 20 seconds. Then, multiply by 3.",
	submit : "Submit",
	back : "Back",
	close : "Close",
	please_select : "Please select",
	password_must_have_at_least : "Password must have at least",
	password_must_have_at_least_2 : "characters",
	password_can_only_have_at : "Password can only have at most",
	password_can_only_have_at_2 : "characters",
    subscribe_to_complete_tasks: " Subscribe to this experiment to complete tasks ",
    confirm_restart_subscription: "Are you sure you want to restart this subscription?. You will lose all progress with your current subscription!",
    confirm_experiment_selection: "Do you want to subscribe to these selected experiments: ",
    confirm_experiment_subscription: "Do you want to subscribe to this experiment: ",
    confirm_parent_experiment_subscription: "Do you want to subscribe to this parent experiment. You will be subscribed to the following sub-experiments:  ",
    subscribe_to_experiment: "Start this Experiment",
    subscribe_to_parent_experiment: "Start Parent Experiment",
    confirm_subscription: "Confirm Subscription",
	confirm_resubscription: "Confirm Resubscription",
    week: "Week",
	click_here_to_find_some: "Click Here to find some!",
	box_description1: "A set of experiments to explore how you \"",
	box_description2: "\"!",
    experiment_type: "Experiment Type",
    experiment_duration: "Experiment Duration",
	whats_next: "What's next?",
	repeat_experiment: "Repeat Experiment",
	next_experiment: "Start the Next Experiment",
	see_also: "Start Another Experiment",
    active_experiments: "ACTIVE EXPERIMENTS",
    suggested_experiments: "SUGGESTED EXPERIMENTS",
    available_experiments: "AVAILABLE EXPERIMENTS",
    completed_experiments: "COMPLETED EXPERIMENTS",
    sub_experiments: "SUB EXPERIMENTS",
    scheduled_experiments: "SCHEDULED EXPERIMENTS",
    no_experiments_in_category: "You do not have any experiments in this category at the moment",
    days_long: "days long",
    starting_on: "Starting On",
};

export default Strings;
