const Strings = {
	today : "Hoy",
	boxes : "Cajas",
	journal : "Diario",
	settings : "Configuración",
	teams : "Equipos",
	email_is_missing : "Falta el correo electrónico",
	please_input_an_email_address : "Por favor ingrese una dirección de correo electrónico",
	password_is_missing : "Falta la contraseña",
	password_confirmation_is : "Falta la confirmación de contraseña",
	passwords_must_match : "Las contraseñas deben coincidir",
	sorry_cannot_submit_this_form: "Lo sentimos no podemos enviar este formulario en este momento",
	user_denied_permissions : "¡Permisos denegados al usuario!",
	sorry_the_invite_code_did_not : "Lo sentimos el código de invitación no correspondía a ningún equipo",
	this_method_should_only_be : "Este método solo debe llamarse cuando el usuario está autenticado",
	welcome_to_spring_2023_xb : "¡Bienvenido a la demostración de XB de primavera de 2023! Elija un cuadro a continuación para comenzar.",
	pick_an_experiment : "Elija un experimento",
	day: "Día",
    days: "Días",
	there_is_nothing_to_do_for : "No hay nada que hacer para este día",
	congratulations_you_have : "¡Felicidades! Has completado este experimento.",
	redo_experiment : "Rehacer experimento",
	about_this_study : "Acerca de este estudio",
	are_you_sure : "Estas seguro",
	this_action_is_irreversible : "Esta acción es irreversible",
	cancel : "Cancelar",
	ok : "DE ACUERDO",
	about : "Acerca de",
	app_theme : "Tema de la aplicación",
	log_out : "Finalizar la sesión",
	you_have_requested_your : "Ha solicitado que se elimine su cuenta. Estaremos en contacto pronto.",
	sorry_your_account_cannot_be : "Lo sentimos, tu cuenta no se puede eliminar en este momento.",
	delete_your_account : "Elimina tu cuenta",
	your_profile : "Tu perfil",
	invite_code_is_missing : "Falta el código de invitación",
	invite_code_must_have_6 : "El código de invitación debe tener 6 dígitos",
	join_a_team : "Únete a un equipo",
	invite_code : "código de invitación",
	an_invite_code_is_a_unique : "Un código de invitación es un código único de 6 dígitos asignado a cada equipo. Pídele al dueño o a cualquier miembro del equipo al que quieras unirte que continúe.",
	team_name_is_missing : "Falta el nombre del equipo",
	create_a_team : "Crea un equipo",
	name : "Nombre",
	the_blueberries : "Los arándanos",
	description : "Descripción",
	your_amazing_team_description : "La increíble descripción de tu equipo",
	once_this_team_is_created_you : "Una vez creado este equipo, puedes comenzar a invitar personas dándoles el código de invitación.",
	you_are_currently_not_in_a : "Actualmente no estás en un equipo",
	join : "Unirse",
	or : "O",
	create_one : "Crea uno",
	you_will_be_able_to_join_this : "Podrás unirte a este equipo nuevamente",
	welcome : "Bienvenido",
	no_description : "Sin descripción",
	members : "Miembros",
	member_s_ : "miembro(s)",
	teams_leaderboard : "Tabla de clasificación de equipos",
	leaderboard : "Tabla de clasificación",
	leave_team : "dejar el equipo",
	this_feature_is_coming_soon : "Esta característica estará disponible próximamente",
	stay_tuned : "Manténganse al tanto",
	you : "Tú",
	owner : "Dueño",
	journal_tabs : "Pestañas del diario",
	you_did_not_have_any_notes : "No tenías ninguna nota para este día",
	you_did_not_have_any : "No tenías ninguna actividad para este día",
	add_a_note : "Añadir una nota",
	note : "Nota",
	a_note_to_your_future_self : "Una nota para tu yo futuro",
	a_summary_of_what_you_have : "Un resumen de lo que has hecho hasta ahora",
	daily : "A diario",
	weekly : "Semanalmente",
	activity : "Actividad",
	your_meal_today_consisted_of : "Su comida de hoy consistió en",
	your_meal_today_consisted_of_2 : "% verde y",
	your_meal_today_consisted_of_3 : "% rojo.",
	sorry_we_do_not_have_any_data : "Lo sentimos, no tenemos ningún dato por ahora",
	feel_free_to_jot_down : "
Siéntete libre de anotar cualquier cosa que quieras recordar de este día. Es sólo para su uso y siéntase libre de editarlo en cualquier momento.",
	next : "Próximo",
	scroll_or_read_to_the_end_to : "Desplácese o lea hasta el final para continuar",
	please_check_this_box_to : "Por favor marque esta casilla para continuar",
	enroll : "¡Inscribirse!",
	just_a_few_things : "Sólo unas cuantas cosas...",
	i_have_read_the_provided : "He leído la información del participante proporcionada y doy mi consentimiento para participar en el estudio",
	i_am_a_member_of_staff_or_a : "Soy miembro del personal o estudiante de la Universidad de Southampton y tengo al menos 18 años.",
	i_understand_that_i_must_be : "Entiendo que debo estar empleado en una facultad o servicio participante, y que en algunas facultades o servicios debo discutir o plantear la participación con mi superior inmediato, según lo indique mi facultad o servicio.",
	i_understand_that_physical : "Entiendo que la actividad física puede suponer un riesgo de lesión y he comprobado que es seguro para mí participar",
	you_have_successfully_reset : "¡Has restablecido exitosamente tu contraseña!",
	new_password : "Nueva contraseña",
	repeat_new_password : "Repetir nueva contraseña",
	you_must_register_with_a : "Debes registrarte con un válido ",
	you_must_register_with_a_2 : " dirección de correo electrónico",
	this_email_is_associated_with : "Este correo electrónico está asociado a una cuenta. Por favor inicia sesión en su lugar",
	register_to_continue : "Regístrate para continuar",
	register : "Regístrese",
	university_email : "Correo electrónico de la universidad",
	password : "Contraseña",
	repeat_password : "Repita la contraseña",
	already_had_an_account_login : "¿Ya tenías una cuenta? Acceso",
	email_or_password_did_not : "El correo electrónico o la contraseña no coinciden con nuestro registro",
	login_to_continue : "Inicia sesión para continuar",
	login : "Acceso",
	email : "Correo electrónico",
	not_yet_a_user_register : "¿Aún no eres usuario? Regístrate",
	forgotten_password : "¿Olvidaste tu contraseña?",
	reset_your_password : "Restablece tu contraseña",
	if_your_email_is_in_our : "Si su correo electrónico está en nuestros registros, le enviaremos un correo electrónico",
	continue : "Continuar",
	confirm_your_account : "Confirma tu cuenta",
	sorry_we_cannot_confirm_this : "Lo sentimos, no podemos confirmar esta cuenta. O ha confirmado su cuenta o ha esperado demasiado para confirmar este correo electrónico. Inicie sesión con sus credenciales registradas y siga las instrucciones.",
	account_confirmed_you_can_now : "Cuenta confirmada. Ahora puedes continuar en la aplicación",
	we_have_sent_you_an_email_to : "Le hemos enviado un correo electrónico para confirmar su cuenta",
	resend_confirmation_email : "Reenviar correo electrónico de confirmación",
	confirmed_login : "¿Confirmado? Acceso",
	percent_completed : "% completado",
	day_s_ : "Día(s)",
	xb_app_logo : "Logotipo de la aplicación XB",
	you_havent_got_any_task_today : "No tienes ninguna tarea hoy",
	explore_what_you_can_do_in : "Las tareas aparecerán aquí cuando hayas iniciado algunos experimentos",
	todays_experiments : "Los experimentos de hoy",
	read : "Lea",
	less : "menos",
	more : "más",
	your_first_name_is_missing : "Falta tu nombre",
	your_last_name_is_missing : "Falta tu apellido",
	department_is_missing : "Falta el departamento",
	lets_roll : "¡Empezamos!",
	first_name : "Nombre",
	last_name : "Apellido",
	department : "Departamento",
	campus : "Campus",
	office : "Oficina",
	exercise_is_safe_and : "El ejercicio es seguro y beneficioso para la mayoría de las personas, pero algunas personas deberían consultar con su médico antes de cambiar sus patrones de actividad física. Usa el",
	par_questionnaire : "Cuestionario PAR",
	exercise_is_safe_and_2 : "y/o consulte a su médico general antes de realizar actividad física.",
	what_move_do_you_want_to_do : "¿Qué movimiento quieres hacer?",
	click_the_button_below_to_add : "Haz clic en el botón que aparece a continuación para agregar un movimiento y luego cronometra el tiempo que tardas en hacerlo. O, si ya lo has hecho por tu cuenta, pulsa Siguiente. Repite el movimiento de 4 a 8 veces si es posible.",
	add : "Agregue",
	tap_on_the_time_display_to : "Pulsa la pantalla de hora para ajustar la hora",
	a_minute_has_passed : "Ha pasado un minuto",
	youtube_video_player : "Reproductor de vídeo de YouTube",
	this_field_must_be_a_number : "Este campo debe ser un número",
	this_field_is_missing : "Falta este campo",
	you_need_to_time_this : "¡Necesitas cronometrar esta actividad!",
	this_field_must_be_checked : "Este campo debe estar marcado",
	retake_another_picture : "Vuelve a tomar otra fotografía",
	take_a_picture : "Toma una fotografía",
	please_review_the_estimation : "Revise la estimación. Tenga en cuenta que los porcentajes no necesariamente suman 100, ya que los ingredientes como el arroz no cuentan como rojos ni como verdes",
	a_good_picture_must_show_your : "Una buena fotografía debe mostrar la comida en su conjunto. Trate de no incluir otros objetos en la fotografía para obtener una estimación precisa",
	green : "Verde (%)",
	red : "Rojo (%)",
	the_original_picture_has_been : "La imagen original ha sido coloreada nuevamente para que puedas ver si la estimación es correcta. Siéntete libre de modificar las estimaciones",
	heart_rate_measure : "Ilustración de medición de la frecuencia cardíaca",
	find_your_pulse_by_firmly : "Encuentra tu pulso agarrándote firmemente la muñeca como en el diagrama que aparece a continuación. Cuenta tus latidos durante 20 segundos. Luego, multiplícalos por 3.",
	submit : "Enviar",
	back : "Atrás",
	close : "Cerca",
	please_select : "Por favor seleccione",
	password_must_have_at_least : "La contraseña debe tener al menos",
	password_must_have_at_least_2 : "caracteres",
	password_can_only_have_at : "La contraseña solo puede tener máximo",
	password_can_only_have_at_2 : "caracteres",
    subscribe_to_complete_tasks: " Suscríbete a este experimento para completar tareas ",
    confirm_restart_subscription: "¿Estás seguro de que deseas reiniciar esta suscripción? ¡Perderás todo el progreso de tu suscripción actual!",
    confirm_experiment_selection: "Quieres suscribirte a estos experimentos seleccionados: ",
    confirm_experiment_subscription: "¿Quieres suscribirte a este experimento: ",
    confirm_parent_experiment_subscription: "¿Quieres suscribirte a este experimento principal? Te suscribirás a los siguientes subexperimentos:  ",
    subscribe_to_experiment: "Comience este experimento",
    subscribe_to_parent_experiment: "Iniciar experimento para padres",
    confirm_subscription: "Confirmar suscripción",
	confirm_resubscription: "Confirmar resuscripción",
    week: "Semana",
	click_here_to_find_some: "¡Haga clic aquí para encontrar algunos!",
	box_description1: "Un conjunto de experimentos para explorar cómo \"",
	box_description2: "\"!",
    experiment_type: "Tipo de experimento",
    experiment_duration: "Duración del experimento",
	whats_next: "¿Que sigue?",
	repeat_experiment: "Repita el experimento",
	next_experiment: "Comience el próximo experimento",
	see_also: "Iniciar otro experimento",
    active_experiments: "EXPERIMENTOS ACTIVOS",
    suggested_experiments: "EXPERIMENTOS SUGERIDOS",
    available_experiments: "EXPERIMENTOS DISPONIBLES",
    completed_experiments: "EXPERIMENTOS COMPLETADOS",
    sub_experiments: "SUBEXPERIMENTOS",
    scheduled_experiments: "EXPERIMENTOS PROGRAMADOS",
    no_experiments_in_category: "No tienes ningún experimento en esta categoría en este momento",
    days_long: "días largos",
    starting_on: "Empezando en",
};

export default Strings;
