const StringsEN = {
    today: 'Today',
    boxes: 'Boxes',
    journal: 'Lab Book',
    settings: 'Settings',
    teams: 'Teams',
    email_is_missing: 'Email is missing',
    please_input_an_email_address: 'Please input an email address',
    password_is_missing: 'Password is missing',
    password_confirmation_is: 'Password confirmation is missing',
    passwords_must_match: 'Passwords must match',
    sorry_cannot_submit_this_form: 'Sorry, cannot submit this form at the moment',
    user_denied_permissions: 'User denied permissions!',
    sorry_the_invite_code_did_not: 'Sorry, the invite code did not correspond to any team',
    this_method_should_only_be: 'This method should only be called when user is authenticated',
    welcome_to_xb:
        'By clicking on any of these boxes, below, you can take a look at each of the experiments in each box.',
    pick_an_experiment: 'Pick an Experiment',
    day: 'Day',
    days: 'Days',
    there_is_nothing_to_do_for: 'There is nothing to do for this day',
    congratulations_you_have: 'Congratulations! You have completed this experiment.',
    redo_experiment: 'Redo experiment',
    about_this_study: 'About this study',
    are_you_sure: 'Are you sure?',
    this_action_is_irreversible: 'This action is irreversible',
    cancel: 'Cancel',
    ok: 'OK',
    about: 'About',
    app_theme: 'App theme',
    log_out: 'Log out',
    you_have_requested_your: 'You have requested your account to be deleted. We will be in touch soon.',
    sorry_your_account_cannot_be: 'Sorry, your account cannot be deleted at the moment.',
    delete_your_account: 'Delete account and withdraw from study',
    your_profile: 'Your Profile',
    invite_code_is_missing: 'Invite code is missing',
    invite_code_must_have_6: 'Invite code must have 6 digits',
    join_a_team: 'Join a team',
    invite_code: 'Invite code',
    an_invite_code_is_a_unique:
        'An invite code is a unique 6-digit code assigned to each team. Ask the owner, or any member of the team you want to join to continue.',
    team_name_is_missing: 'Team name is missing',
    create_a_team: 'Create a team',
    name: 'Name',
    the_blueberries: 'The Blueberries',
    description: 'Description',
    your_amazing_team_description: 'Your amazing team description',
    once_this_team_is_created_you:
        'Once this team is created, you can start inviting people by giving them the invite code.',
    you_are_currently_not_in_a: 'You are currently not in a team',
    join: 'Join',
    or: 'Or',
    create_one: 'Create one',
    you_will_be_able_to_join_this: 'You will be able to join this team again',
    welcome: 'Welcome',
    no_description: 'No description',
    members: 'Members',
    member_s_: 'member(s)',
    teams_leaderboard: 'Teams leaderboard',
    leaderboard: 'Leaderboard',
    leave_team: 'Leave team',
    this_feature_is_coming_soon: 'This feature is coming soon',
    stay_tuned: 'Stay Tuned',
    you: 'You',
    owner: 'Owner',
    journal_tabs: 'Journal tabs',
    you_did_not_have_any_notes: 'No notes were recorded on this day',
    you_did_not_have_any: 'No activities were recorded on this day',
    add_a_note: 'Add a note',
    note: 'Note',
    a_note_to_your_future_self: 'A note to your future self',
    a_summary_of_what_you_have: 'A summary of what you have done so far',
    daily: 'Daily',
    weekly: 'Weekly',
    activity: 'Activity',
    your_meal_today_consisted_of: 'Your meal today consisted of',
    your_meal_today_consisted_of_2: '% green and',
    your_meal_today_consisted_of_3: '% red.',
    sorry_we_do_not_have_any_data: 'Sorry, we do not have any data for now',
    feel_free_to_jot_down:
        'Feel free to jot down anything that you want to look back for this day. It is for your use only, and feel free to edit it anytime.',
    previous: 'Back',
    next: 'Next',
    scroll_or_read_to_the_end_to: 'Scroll or read to the end to continue',
    please_check_this_box_to: 'Please check this box to continue',
    enroll: 'Enroll!',
    finish: 'Finish',
    just_a_few_things: 'Just a Few Things...',
    i_have_read_the_provided: 'I have read the provided participant information and consent to take part in the study',
    i_am_a_member_of_staff_or_a:
        'I am a member of staff or a student at the University of Southampton, and I am at least 18 years old.',
    i_understand_that_i_must_be:
        'I understand that I must be employed in a participating faculty or service, and that in some faculties or services I should discuss or raise participation with my line manager, as directed by my faculty or service.',
    i_understand_that_physical:
        'I understand that physical activity can pose the risk of injury, and I have checked that it is safe for me to take part',
    you_have_successfully_reset: 'You have successfully reset your password!',
    new_password: 'New password',
    repeat_new_password: 'Repeat new password',
    you_must_register_with_a: 'You must register with a valid ',
    you_must_register_with_a_2: ' email address',
    this_email_is_associated_with: 'This email is associated with an account. Please log in instead',
    register_to_continue: 'Register to continue',
    register: 'Register',
    university_email: 'University email',
    password: 'Password',
    repeat_password: 'Repeat password',
    already_had_an_account_login: 'Already have an account? Login',
    email_or_password_did_not: 'Email or password did not match our record',
    login_error: 'An error occurred while attempting to login, please check your credentials and try again.',
    login_to_continue: 'Login to continue',
    login: 'Login',
    email: 'Email',
    not_yet_a_user_register: 'Not yet a user? Register',
    forgotten_password: 'Forgotten password?',
    reset_your_password: 'Reset your password',
    if_your_email_is_in_our: 'If your email is in our records, we will send you an email',
    continue: 'Continue',
    confirm_your_account: 'Confirm your account',
    sorry_we_cannot_confirm_this:
        'Sorry, we cannot confirm this account. You have either confirmed your account, or have waited too long to confirm this email. Please login with your registered credentials and follow the instructions.',
    account_confirmed_you_can_now: 'Account confirmed. You can now continue in the app',
    we_have_sent_you_an_email_to: 'We have sent you an email to confirm your account',
    resend_confirmation_email: 'Resend confirmation email',
    confirmed_login: 'Confirmed? Login',
    percent_completed: '% completed',
    day_s_: 'Day(s)',
    xb_app_logo: 'XB App logo',
    you_havent_got_any_task_today: "You haven't got any tasks today",
    you_have_unfinished_tasks_from_previous_days: "You've pending tasks from previous days!",
    explore_what_you_can_do_in: 'Tasks will appear here when you have started some experiments',
    todays_experiments: "Today's Experiments",
    read: 'Read',
    less: 'less',
    more: 'more',
    your_first_name_is_missing: 'Your first name is missing',
    your_last_name_is_missing: 'Your last name is missing',
    department_is_missing: 'Department is missing',
    lets_roll: 'Lets roll!',
    first_name: 'First name',
    last_name: 'Last name',
    department: 'Department',
    campus: 'Campus',
    office: 'Office',
    exercise_is_safe_and:
        'Exercise is safe and beneficial for most people, but some people should check with their doctor before changing their physical activity patterns. Use the',
    par_questionnaire: 'PAR Questionnaire',
    exercise_is_safe_and_2: 'and/or consult your GP before engaging in physical activity.',
    what_move_do_you_want_to_do: 'What move do you want to do?',
    click_the_button_below_to_add:
        'Click the button below to add a movement, then time yourself doing it. Or if you have done it in on your own, tap Next. Repeat 4 to 8 times if possible.',
    add: 'Add',
    tap_on_the_time_display_to: 'Tap on the time display to adjust time',
    a_minute_has_passed: 'A minute has passed',
    youtube_video_player: 'YouTube video player',
    this_field_must_be_a_number: 'This field must be a number',
    this_field_is_missing: 'This field is missing',
    you_need_to_time_this: 'You need to time this activity!',
    this_field_must_be_checked: 'This field must be checked',
    retake_another_picture: 'Retake another picture',
    take_a_picture: 'Take a picture',
    please_review_the_estimation:
        'Please review the estimation. Note that the percentages do not necessarily add up to 100 as ingredients like rice counts neither as red nor green',
    a_good_picture_must_show_your:
        'A good picture must show your meal as a whole. Try not to get other objects in the picture to get an accurate estimation',
    green: 'Green (%)',
    red: 'Red (%)',
    the_original_picture_has_been:
        'The original picture has been re-coloured for you to see if the estimation is correct. Feel free to modify the estimations',
    heart_rate_measure: 'Heart rate measure illustration',
    find_your_pulse_by_firmly:
        'Find your pulse by firmly gripping your wrist like in the diagram below. Count your heartbeats for 20 seconds. Then, multiply by 3.',
    submit: 'Submit',
    back: 'Back',
    close: 'Close',
    please_select: 'Please select',
    password_must_have_at_least: 'Password must have at least',
    password_must_have_at_least_2: 'characters',
    password_can_only_have_at: 'Password can only have at most',
    password_can_only_have_at_2: 'characters',
    subscribe_to_complete_tasks: ' Subscribe to this experiment to complete tasks ',
    confirm_restart_subscription:
        'Are you sure you want to restart this subscription?. You will lose all progress with your current subscription!',
    confirm_experiment_selection: 'Do you want to subscribe to these selected experiments: ',
    confirm_experiment_subscription: 'Do you want to subscribe to this box ?',
    subscribe_to_box: 'Like the look of this box? Subscribe to join in!',
    already_subscribed: 'You are subscribed to this box',
    confirm_subscription: 'Confirm Subscription',
    subscribe: 'Subscribe',
    resubscribe: 'Resubscribe',
    confirm_resubscription: 'Confirm Resubscription',
    week: 'Week',
    click_here_to_find_some: 'Explore the boxes',
    box_description1: 'A set of experiments to explore how you "',
    box_description2: '"!',
    experiment_type: 'Experiment Type',
    experiment_duration: 'Experiment Duration',
    whats_next: "What's next?",
    repeat_experiment: 'Repeat Experiment',
    next_experiment: 'Start the Next Experiment',
    active_experiments: 'ACTIVE EXPERIMENTS',
    suggested_experiments: 'SUGGESTED EXPERIMENTS',
    available_experiments: 'CLICK any of these BOXES to see Each Week’s Experiment',
    completed_experiments: 'COMPLETED EXPERIMENTS',
    scheduled_experiments: 'SCHEDULED EXPERIMENTS',
    no_experiments_in_category: 'You do not have any experiments in this category at the moment',
    days_long: 'days long',
    starting_on: 'Starting On',
    of: 'of',
    not_subscribed_to_experiment: 'You are not currently subscribed to this experiment.',
    has_cohort_code: 'Do you have a cohort code ?',
    cohort_code: 'Cohort code',
    cohort_code_required: 'You have indicated that you have a cohort code. Please enter it before you can proceed.',
    cohort_code_invalid: 'A cohort does not exist for the code you have provided. Please check the code and try again.',
    overview: 'OVERVIEW',
    prep: 'PREPARATIONS',
    steps: 'STEPS',
    reflections: 'REFLECTIONS',
    checks: 'CHECKS',
    tips: 'TIPS',
    preview: 'PREVIEW of ',
    day_progress: 'S',
    adjust_how_app_works: 'Adjust how the app works for you',
};

const StringsES: typeof StringsEN = {
    today: 'Hoy',
    boxes: 'Cajas',
    journal: 'Diario',
    settings: 'Configuración',
    teams: 'Equipos',
    email_is_missing: 'Falta el correo electrónico',
    please_input_an_email_address: 'Por favor ingrese una dirección de correo electrónico',
    password_is_missing: 'Falta la contraseña',
    password_confirmation_is: 'Falta la confirmación de contraseña',
    passwords_must_match: 'Las contraseñas deben coincidir',
    sorry_cannot_submit_this_form: 'Lo sentimos no podemos enviar este formulario en este momento',
    user_denied_permissions: '¡Permisos denegados al usuario!',
    sorry_the_invite_code_did_not: 'Lo sentimos el código de invitación no correspondía a ningún equipo',
    this_method_should_only_be: 'Este método solo debe llamarse cuando el usuario está autenticado',
    welcome_to_xb:
        '¡Bienvenido a la demostración de XB de primavera de 2023! Elija un cuadro a continuación para comenzar.',
    pick_an_experiment: 'Elija un experimento',
    day: 'Día',
    days: 'Días',
    there_is_nothing_to_do_for: 'No hay nada que hacer para este día',
    congratulations_you_have: '¡Felicidades! Has completado este experimento.',
    redo_experiment: 'Rehacer experimento',
    about_this_study: 'Acerca de este estudio',
    are_you_sure: 'Estas seguro',
    this_action_is_irreversible: 'Esta acción es irreversible',
    cancel: 'Cancelar',
    ok: 'DE ACUERDO',
    about: 'Acerca de',
    app_theme: 'Tema de la aplicación',
    log_out: 'Finalizar la sesión',
    you_have_requested_your: 'Ha solicitado que se elimine su cuenta. Estaremos en contacto pronto.',
    sorry_your_account_cannot_be: 'Lo sentimos, tu cuenta no se puede eliminar en este momento.',
    delete_your_account: 'Elimina tu cuenta',
    your_profile: 'Tu perfil',
    invite_code_is_missing: 'Falta el código de invitación',
    invite_code_must_have_6: 'El código de invitación debe tener 6 dígitos',
    join_a_team: 'Únete a un equipo',
    invite_code: 'código de invitación',
    an_invite_code_is_a_unique:
        'Un código de invitación es un código único de 6 dígitos asignado a cada equipo. Pídele al dueño o a cualquier miembro del equipo al que quieras unirte que continúe.',
    team_name_is_missing: 'Falta el nombre del equipo',
    create_a_team: 'Crea un equipo',
    name: 'Nombre',
    the_blueberries: 'Los arándanos',
    description: 'Descripción',
    your_amazing_team_description: 'La increíble descripción de tu equipo',
    once_this_team_is_created_you:
        'Una vez creado este equipo, puedes comenzar a invitar personas dándoles el código de invitación.',
    you_are_currently_not_in_a: 'Actualmente no estás en un equipo',
    join: 'Unirse',
    or: 'O',
    create_one: 'Crea uno',
    you_will_be_able_to_join_this: 'Podrás unirte a este equipo nuevamente',
    welcome: 'Bienvenido',
    no_description: 'Sin descripción',
    members: 'Miembros',
    member_s_: 'miembro(s)',
    teams_leaderboard: 'Tabla de clasificación de equipos',
    leaderboard: 'Tabla de clasificación',
    leave_team: 'dejar el equipo',
    this_feature_is_coming_soon: 'Esta característica estará disponible próximamente',
    stay_tuned: 'Manténganse al tanto',
    you: 'Tú',
    owner: 'Dueño',
    journal_tabs: 'Pestañas del diario',
    you_did_not_have_any_notes: 'No tenías ninguna nota para este día',
    you_did_not_have_any: 'No tenías ninguna actividad para este día',
    add_a_note: 'Añadir una nota',
    note: 'Nota',
    a_note_to_your_future_self: 'Una nota para tu yo futuro',
    a_summary_of_what_you_have: 'Un resumen de lo que has hecho hasta ahora',
    daily: 'A diario',
    weekly: 'Semanalmente',
    activity: 'Actividad',
    your_meal_today_consisted_of: 'Su comida de hoy consistió en',
    your_meal_today_consisted_of_2: '% verde y',
    your_meal_today_consisted_of_3: '% rojo.',
    sorry_we_do_not_have_any_data: 'Lo sentimos, no tenemos ningún dato por ahora',
    feel_free_to_jot_down:
        'Siéntete libre de anotar cualquier cosa que quieras recordar de este día. Es sólo para su uso y siéntase libre de editarlo en cualquier momento.',
    previous: 'Anterior',
    next: 'Próximo',
    scroll_or_read_to_the_end_to: 'Desplácese o lea hasta el final para continuar',
    please_check_this_box_to: 'Por favor marque esta casilla para continuar',
    enroll: '¡Inscribirse!',
    finish: 'Terminar',
    just_a_few_things: 'Sólo unas cuantas cosas...',
    i_have_read_the_provided:
        'He leído la información del participante proporcionada y doy mi consentimiento para participar en el estudio',
    i_am_a_member_of_staff_or_a:
        'Soy miembro del personal o estudiante de la Universidad de Southampton y tengo al menos 18 años.',
    i_understand_that_i_must_be:
        'Entiendo que debo estar empleado en una facultad o servicio participante, y que en algunas facultades o servicios debo discutir o plantear la participación con mi superior inmediato, según lo indique mi facultad o servicio.',
    i_understand_that_physical:
        'Entiendo que la actividad física puede suponer un riesgo de lesión y he comprobado que es seguro para mí participar',
    you_have_successfully_reset: '¡Has restablecido exitosamente tu contraseña!',
    new_password: 'Nueva contraseña',
    repeat_new_password: 'Repetir nueva contraseña',
    you_must_register_with_a: 'Debes registrarte con un válido ',
    you_must_register_with_a_2: ' dirección de correo electrónico',
    this_email_is_associated_with:
        'Este correo electrónico está asociado a una cuenta. Por favor inicia sesión en su lugar',
    register_to_continue: 'Regístrate para continuar',
    register: 'Regístrese',
    university_email: 'Correo electrónico de la universidad',
    password: 'Contraseña',
    repeat_password: 'Repita la contraseña',
    already_had_an_account_login: '¿Ya tenías una cuenta? Acceso',
    email_or_password_did_not: 'El correo electrónico o la contraseña no coinciden con nuestro registro',
    login_error: 'Error al iniciar sesión',
    login_to_continue: 'Inicia sesión para continuar',
    login: 'Acceso',
    email: 'Correo electrónico',
    not_yet_a_user_register: '¿Aún no eres usuario? Regístrate',
    forgotten_password: '¿Olvidaste tu contraseña?',
    reset_your_password: 'Restablece tu contraseña',
    if_your_email_is_in_our: 'Si su correo electrónico está en nuestros registros, le enviaremos un correo electrónico',
    continue: 'Continuar',
    confirm_your_account: 'Confirma tu cuenta',
    sorry_we_cannot_confirm_this:
        'Lo sentimos, no podemos confirmar esta cuenta. O ha confirmado su cuenta o ha esperado demasiado para confirmar este correo electrónico. Inicie sesión con sus credenciales registradas y siga las instrucciones.',
    account_confirmed_you_can_now: 'Cuenta confirmada. Ahora puedes continuar en la aplicación',
    we_have_sent_you_an_email_to: 'Le hemos enviado un correo electrónico para confirmar su cuenta',
    resend_confirmation_email: 'Reenviar correo electrónico de confirmación',
    confirmed_login: '¿Confirmado? Acceso',
    percent_completed: '% completado',
    day_s_: 'Día(s)',
    xb_app_logo: 'Logotipo de la aplicación XB',
    you_havent_got_any_task_today: 'No tienes ninguna tarea hoy',
    explore_what_you_can_do_in: 'Las tareas aparecerán aquí cuando hayas iniciado algunos experimentos',
    todays_experiments: 'Los experimentos de hoy',
    read: 'Lea',
    less: 'menos',
    more: 'más',
    your_first_name_is_missing: 'Falta tu nombre',
    your_last_name_is_missing: 'Falta tu apellido',
    department_is_missing: 'Falta el departamento',
    lets_roll: '¡Empezamos!',
    first_name: 'Nombre',
    last_name: 'Apellido',
    department: 'Departamento',
    campus: 'Campus',
    office: 'Oficina',
    exercise_is_safe_and:
        'El ejercicio es seguro y beneficioso para la mayoría de las personas, pero algunas personas deberían consultar con su médico antes de cambiar sus patrones de actividad física. Usa el',
    par_questionnaire: 'Cuestionario PAR',
    exercise_is_safe_and_2: 'y/o consulte a su médico general antes de realizar actividad física.',
    what_move_do_you_want_to_do: '¿Qué movimiento quieres hacer?',
    click_the_button_below_to_add:
        'Haz clic en el botón que aparece a continuación para agregar un movimiento y luego cronometra el tiempo que tardas en hacerlo. O, si ya lo has hecho por tu cuenta, pulsa Siguiente. Repite el movimiento de 4 a 8 veces si es posible.',
    add: 'Agregue',
    tap_on_the_time_display_to: 'Pulsa la pantalla de hora para ajustar la hora',
    a_minute_has_passed: 'Ha pasado un minuto',
    youtube_video_player: 'Reproductor de vídeo de YouTube',
    this_field_must_be_a_number: 'Este campo debe ser un número',
    this_field_is_missing: 'Falta este campo',
    you_need_to_time_this: '¡Necesitas cronometrar esta actividad!',
    this_field_must_be_checked: 'Este campo debe estar marcado',
    retake_another_picture: 'Vuelve a tomar otra fotografía',
    take_a_picture: 'Toma una fotografía',
    please_review_the_estimation:
        'Revise la estimación. Tenga en cuenta que los porcentajes no necesariamente suman 100, ya que los ingredientes como el arroz no cuentan como rojos ni como verdes',
    a_good_picture_must_show_your:
        'Una buena fotografía debe mostrar la comida en su conjunto. Trate de no incluir otros objetos en la fotografía para obtener una estimación precisa',
    green: 'Verde (%)',
    red: 'Rojo (%)',
    the_original_picture_has_been:
        'La imagen original ha sido coloreada nuevamente para que puedas ver si la estimación es correcta. Siéntete libre de modificar las estimaciones',
    heart_rate_measure: 'Ilustración de medición de la frecuencia cardíaca',
    find_your_pulse_by_firmly:
        'Encuentra tu pulso agarrándote firmemente la muñeca como en el diagrama que aparece a continuación. Cuenta tus latidos durante 20 segundos. Luego, multiplícalos por 3.',
    submit: 'Enviar',
    back: 'Atrás',
    close: 'Cerca',
    please_select: 'Por favor seleccione',
    password_must_have_at_least: 'La contraseña debe tener al menos',
    password_must_have_at_least_2: 'caracteres',
    password_can_only_have_at: 'La contraseña solo puede tener máximo',
    password_can_only_have_at_2: 'caracteres',
    subscribe_to_complete_tasks: ' Suscríbete a este experimento para completar tareas ',
    confirm_restart_subscription:
        '¿Estás seguro de que deseas reiniciar esta suscripción? ¡Perderás todo el progreso de tu suscripción actual!',
    confirm_experiment_selection: 'Quieres suscribirte a estos experimentos seleccionados: ',
    confirm_experiment_subscription: '¿Quieres suscribirte a este experimento: ',
    confirm_subscription: 'Confirmar suscripción',
    confirm_resubscription: 'Confirmar resuscripción',
    week: 'Semana',
    click_here_to_find_some: '¡Haga clic aquí para encontrar algunos!',
    box_description1: 'Un conjunto de experimentos para explorar cómo "',
    box_description2: '"!',
    experiment_type: 'Tipo de experimento',
    experiment_duration: 'Duración del experimento',
    whats_next: '¿Que sigue?',
    repeat_experiment: 'Repita el experimento',
    next_experiment: 'Comience el próximo experimento',
    active_experiments: 'EXPERIMENTOS ACTIVOS',
    suggested_experiments: 'EXPERIMENTOS SUGERIDOS',
    available_experiments: 'EXPERIMENTOS DISPONIBLES',
    completed_experiments: 'EXPERIMENTOS COMPLETADOS',
    scheduled_experiments: 'EXPERIMENTOS PROGRAMADOS',
    no_experiments_in_category: 'No tienes ningún experimento en esta categoría en este momento',
    days_long: 'días largos',
    starting_on: 'Empezando en',
    subscribe_to_box: 'Suscríbete a esta caja',
    already_subscribed: 'Ya estás suscrito a esta caja',
    of: 'of',
    not_subscribed_to_experiment: 'No estás suscrito actualmente a este experimento.',
    has_cohort_code: '¿Tienes un código de cohorte ?',
    cohort_code: 'Cohort code',
    cohort_code_required: 'You have indicated that you have a cohort code. Please enter it before you can proceed.',
    cohort_code_invalid: 'A cohort does not exist for the code you have provided. Please check the code and try again.',
    overview: 'OVERVIEW',
    prep: 'PREPARATIONS',
    steps: 'STEPS',
    reflections: 'REFLECTIONS',
    checks: 'CHECKS',
    tips: 'TIPS',
    you_have_unfinished_tasks_from_previous_days: 'Tienes tareas sin terminar de los días anteriores',
    subscribe: 'Suscríbete',
    resubscribe: 'Resuscríbete',
    preview: 'Vista previa',
    day_progress: 'Progreso del día',
    adjust_how_app_works: 'Ajusta cómo funciona la app para ti',
};

const langIndex = localStorage.getItem('lang') ?? '0';

const Strings = langIndex == '0' ? StringsEN : StringsES;

export default Strings;
